server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/renda?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
mybatis:
  type-aliases-package: cn.renda.service.pojo