server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/renda
    username: root
    password: root
    hikari:
      max-lifetime: 28830000 # 一个连接的生命时长ms，超时而且没被使用则被释放，默认:30分钟，建议设置比数据库超时时长少30秒
      maximum-pool-size: 9 # 连接池中允许的最大连接数。默认值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
