server:
  port: 10010
spring:
  application:
    name: xxx-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5 # 开发阶段调低数值
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** # 商品微服务的映射路径
    search-service: /search/** # 搜索功能微服务的映射路径
    user-service: /user/** # 用户微服务的映射路径
    auth-service: /auth/** # 授权中心微服务
  ignored-services: # 忽略upload-service服务，避免网络阻塞
    - upload-service
  add-host-header: true # 携带请求本身的头信息
  sensitive-headers: # 配置禁止使用的头信息，这里设置为 null，否则 set-cookie 无效。
  host:
    socket-timeout-millis: 10000 # socket 超时为 10 秒
    connect-timeout-millis: 6000 # HTTP 连接超时为 6 秒。要比 Hystrix 的大
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 # 设置hystrix的超时时间为5000ms
ribbon:
  ReadTimeout: 4000 # 注意ribbon的超时时间要小于zuul超时时间
  ConnectTimeout: 4000