server:
  port: 10010
spring:
  application:
    name: xxx-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5 # 开发阶段调低数值
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** # 商品微服务的映射路径
  ignored-services:
    - upload-service # 忽略upload-service服务，避免网络阻塞