server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq: # 只是接收消息而不发送，所以不用配置template相关内容。
    host: 127.0.0.1
    username: /xxx
    password: xxx
    virtual-host: /xxx
xxx:
  sms:
    accessKeyId: YOUR_ACCESSS_KEY_ID # 阿里云RAM访问控制里生成的accessKeyId
    accessKeySecret: YOUR_ACCESS_KEY_SECRET # 阿里云RAM访问控制里生成的AccessKeySecret
    signName: XXX商城 # 阿里云短信服务自定义的签名名称
    verifyCodeTemplate: SMS_190215386 # 阿里云短信服务自定义的模板名称